@host = https://pbec2207-main-server.onrender.com/v1
//@host = http://localhost:6000/v1
### add delivery info
POST {{host}}/delivery/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EwZDU1YjEwOGUxMmQyZGQxNzk0ZmUiLCJuaWNrTmFtZSI6IiIsInVzZXJOYW1lIjoiVGVzdCAwMSIsInJvbGUiOiJ1c2VyIiwibWV0YSI6eyJ0b3RhbEJ1eSI6MCwidG90YWxDYW5jZWwiOjB9LCJzcGVjaWFsIjpbXSwidHlwZUxvZ2luIjoibG9jYWwiLCJpYXQiOjE2NzE0ODQ5MTEsImV4cCI6MTY3NDA3NjkxMX0.p7AXrybEqGZ7ct2ZKDaonpzuAs4ICgsEDQgNEJrt0h0

{
  "address":{
    "name":"Baby pig 123",
    "zipCode": 63000,
    "phoneNumber":"05003539181",
    "address":"123/1 Hoang dieu 2, Tp. Thu Duc",
    "addressCode":{
      "district":1,
      "province":3,
      "ward": 2,
      "street":222
    },
    "code":1
  }
}

### get delivery info
GET {{host}}/delivery/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc5NDYzNzkzMDFlMGU4YjgxNmViNjgiLCJuaWNrTmFtZSI6IiIsInVzZXJOYW1lIjoiQmFvIFRyYW4iLCJyb2xlIjoidXNlciIsIm1ldGEiOnsidG90YWxCdXkiOjAsInRvdGFsQ2FuY2VsIjowfSwic3BlY2lhbCI6W10sInR5cGVMb2dpbiI6ImxvY2FsIiwiaWF0IjoxNjcxNDI5Mzc1LCJleHAiOjE2NzQwMjEzNzV9.KY9g2Ivkm1PPh6VWN2-sP_lghHlJtLIyklS63QnJ1iI

{

}

### remove delivery info by address Id
POST {{host}}/delivery/delete
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2Mzc5NDYzNzkzMDFlMGU4YjgxNmViNjgiLCJuaWNrTmFtZSI6IiIsInVzZXJOYW1lIjoiQmFvIFRyYW4iLCJyb2xlIjoidXNlciIsIm1ldGEiOnsidG90YWxCdXkiOjAsInRvdGFsQ2FuY2VsIjowfSwic3BlY2lhbCI6W10sInR5cGVMb2dpbiI6ImxvY2FsIiwiaWF0IjoxNjcxNDI5Mzc1LCJleHAiOjE2NzQwMjEzNzV9.KY9g2Ivkm1PPh6VWN2-sP_lghHlJtLIyklS63QnJ1iI

{
  "addressId":"63a0d710108e12d2dd17951e"
}

### update delivery info
PUT {{host}}/delivery/update
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EwZDU1YjEwOGUxMmQyZGQxNzk0ZmUiLCJuaWNrTmFtZSI6IiIsInVzZXJOYW1lIjoiVGVzdCAwMSIsInJvbGUiOiJ1c2VyIiwibWV0YSI6eyJ0b3RhbEJ1eSI6MCwidG90YWxDYW5jZWwiOjB9LCJzcGVjaWFsIjpbXSwidHlwZUxvZ2luIjoibG9jYWwiLCJpYXQiOjE2NzE2Nzk1MTksImV4cCI6MTY3MTc2NTkxOX0.6ZIyVlxDtOEEuxkK2O2QsK_oF4Z7bxIUMRvKTUr4sZQ

{
  "addressId":"63a3cd1e29d02de094034509",
  "address":{
    "name":"Chuppy 123",
    "zipCode": 63000,
    "phoneNumber":"0987654321",
    "address":"123/1 Hoang dieu 2, Tp. Thu Duc",
    "addressCode":{
      "district":1,
      "province":3,
      "ward": 2,
      "street":222
    },
    "code":1
  }
}

### set default delivery info
PUT {{host}}/delivery/set-default
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2M2EwZDU1YjEwOGUxMmQyZGQxNzk0ZmUiLCJuaWNrTmFtZSI6IiIsInVzZXJOYW1lIjoiVGVzdCAwMSIsInJvbGUiOiJ1c2VyIiwibWV0YSI6eyJ0b3RhbEJ1eSI6MCwidG90YWxDYW5jZWwiOjB9LCJzcGVjaWFsIjpbXSwidHlwZUxvZ2luIjoibG9jYWwiLCJpYXQiOjE2NzE2Nzk1MTksImV4cCI6MTY3MTc2NTkxOX0.6ZIyVlxDtOEEuxkK2O2QsK_oF4Z7bxIUMRvKTUr4sZQ

{
  "addressId": "63a3cd1e29d02de094034509"
}